FROM alpine:3.14 AS builder-base
# install build dependencies
RUN apk add --no-cache --update git nodejs npm

# ---
FROM builder-base AS builder
ENV REPO https://github.com/joinmarket-webui/joinmarket-webui
ENV REPO_BRANCH master
ENV REPO_REF master

WORKDIR /usr/src/app

# checkout and build project
RUN git clone "$REPO" . --depth=10 --branch "$REPO_BRANCH" && git checkout "$REPO_REF"
RUN npm install

# ---
FROM builder-base

WORKDIR /app

COPY --from=builder /usr/src/app .
EXPOSE 3000
CMD ["npm", "start"]
