name: 'build-ui-only'

on:
  push:
    branches: [ master, devel ]
    paths:
      - 'ui-only/**'
  pull_request:
    branches: [ master, devel ]
    paths:
      - 'ui-only/**'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
         context: [ ui-only ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: joinmarket-webui/jam-${{ matrix.context }}-ci
          labels: |
            org.opencontainers.image.title=jam-${{ matrix.context }}
            org.opencontainers.image.version=0.0.0
            org.opencontainers.image.description=Jam CI Build (${{ matrix.context }})

      - name: Build and push Docker image for ${{ matrix.context }}
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          context: ./${{ matrix.context }}
          outputs: type=cacheonly
          cache-from: type=gha
          cache-to: type=gha
          #platforms: linux/amd64,linux/arm64
          platforms: linux/arm64
          push: false
          tags: joinmarket-webui/jam-${{ matrix.context }}-ci
          labels: ci
          build-args: |
            JAM_REPO_REF=master
            SKIP_RELEASE_VERIFICATION=true
