name: 'dispatch: check and update dependencies'

on:
  workflow_dispatch:

jobs:
  readenv:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      ui_repo_url: ${{ steps.dotenv.outputs.jam_repo }}
      ui_repo_ref: ${{ steps.dotenv.outputs.jam_repo_ref }}
      jm_ng_repo_url: ${{ steps.dotenv.outputs.jm_ng_repo }}
      jm_ng_repo_ref: ${{ steps.dotenv.outputs.jm_ng_repo_ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Read .env file
        id: dotenv
        uses: falti/dotenv-action@v1.2.0
        with:
          log-variables: true

  check-ui:
    uses: ./.github/workflows/update-dependency-version.yml
    needs: readenv
    with:
      repo_url: ${{ needs.readenv.outputs.ui_repo_url }}
      current_tag: ${{ needs.readenv.outputs.ui_repo_ref }}
      env_var_name: 'JAM_REPO_REF'

  check-joinmarket-ng:
    uses: ./.github/workflows/update-dependency-version.yml
    needs: readenv
    with:
      repo_url: ${{ needs.readenv.outputs.jm_ng_repo_url }}
      current_tag: ${{ needs.readenv.outputs.jm_ng_repo_ref }}
      env_var_name: 'JM_NG_REPO_REF'
