name: Check and update versions of dependencies

on:
  schedule:
    - cron: '51 6 * * *' # every day at 06:51 UTC
  workflow_dispatch:

jobs:
  readenv:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      ui_repo_url: ${{ steps.dotenv.outputs.jm_ui_repo }}
      ui_repo_ref: ${{ steps.dotenv.outputs.jm_ui_repo_ref }}
      server_repo_url: ${{ steps.dotenv.outputs.jm_server_repo }}
      server_repo_ref: ${{ steps.dotenv.outputs.jm_server_repo_ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .env file
        id: dotenv
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true

  check-ui:
    uses: ./.github/workflows/update-dependency-version.yml
    needs: readenv
    with:
      repo_url: ${{ needs.readenv.outputs.ui_repo_url }}
      current_tag: ${{ needs.readenv.outputs.ui_repo_ref }}
      env_var_name: 'JM_UI_REPO_REF'

  check-server:
    uses: ./.github/workflows/update-dependency-version.yml
    needs: readenv
    with:
      repo_url: ${{ needs.readenv.outputs.server_repo_url }}
      current_tag: ${{ needs.readenv.outputs.server_repo_ref }}
      env_var_name: 'JM_SERVER_REPO_REF'
