
name: Create and publish Docker image

on:
  workflow_dispatch:
    inputs:
      version_ref:
        description: 'docker app version (e.g. v21.0.0)'
        required: true
      ui_version_ref:
        description: 'web-ui version/branch (e.g. v1.2.3, master, etc.)'
        required: true
        default: 'v0.2.0'
      server_version_ref:
        description: 'server version/branch (e.g. v1.2.3, master, etc.)'
        required: true
        default: 'v0.9.4'

env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_PREFIX: theborakompanioni/joinmarket-webui-

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
         context: [standalone,ui-only]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .env file
        id: dotenv
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true

      - name: Log in to the Container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}${{ matrix.context }}
          labels: |
            org.opencontainers.image.title=joinmarket-webui-${{ matrix.context }}

      - name: Build and push Docker image for ${{ matrix.context }}
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./${{ matrix.context }}
          #platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JM_UI_REPO_BRANCH=${{ steps.dotenv.outputs.jm_ui_repo_branch }}
            JM_UI_REPO_REF=${{ steps.dotenv.outputs.jm_ui_repo_ref }}
            JM_SERVER_REPO_BRANCH=${{ steps.dotenv.outputs.jm_server_repo_branch }}
            JM_SERVER_REPO_REF=${{ steps.dotenv.outputs.jm_server_repo_ref }}