
name: Manually create and publish Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'docker app version (e.g. v21.0.0)'
        required: true
      ui_repo_ref:
        description: 'web-ui version/branch (e.g. v0.0.2, master, etc.)'
        required: true
        default: 'master'
      server_repo_ref:
        description: 'server version/branch (e.g. v0.9.4, master, etc.)'
        required: true
        default: 'master'

env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_PREFIX: theborakompanioni/jmui-dev-

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
         context: [standalone,ui-only]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true

      - name: Log in to the Container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}${{ matrix.context }}
          labels: |
            org.opencontainers.image.title=joinmarket-webui-${{ matrix.context }}
            org.opencontainers.image.version=${{ github.event.inputs.version }}-dev

      - name: Build and push Docker image for ${{ matrix.context }}
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JM_UI_REPO_REF=${{ github.event.inputs.ui_repo_ref }}
            JM_SERVER_REPO_REF=${{ github.event.inputs.ui_repo_ref }}