name: 'dispatch: build & publish dev docker images'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'docker app version (e.g. v21.0.0)'
        required: true
        type: string
      ui_repo_ref:
        description: 'ui version/branch (e.g. v0.4.1, master, etc.)'
        required: true
        default: 'master'
        type: string
      server_repo_ref:
        description: 'server version/branch (e.g. v0.9.6, master, etc.)'
        required: true
        default: 'master'
        type: string
      skip_release_verification:
        description: 'enable skipping release verification'
        required: false
        default: false
        type: boolean

jobs:
  image-manually:
    uses: ./.github/workflows/create-and-publish-docker.yml
    with:
      version: ${{ github.event.inputs.version }}-dev
      ui_repo_ref: ${{ github.event.inputs.ui_repo_ref }}
      server_repo_ref: ${{ github.event.inputs.server_repo_ref }}
      image_name_prefix: joinmarket-webui/jam-dev-
      skip_release_verification: ${{ github.event.inputs.skip_release_verification == 'true' }}
