name: Manually create and publish Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'docker app version (e.g. v21.0.0)'
        required: true
        type: string
      ui_repo_ref:
        description: 'web-ui version/branch (e.g. v0.0.2, master, etc.)'
        required: true
        default: 'master'
        type: string
      server_repo_ref:
        description: 'server version/branch (e.g. v0.9.4, master, etc.)'
        required: true
        default: 'master'
        type: string

jobs:
  image-manually:
    uses: ./.github/workflows/create-and-publish-docker.yml
    with:
      version: ${{ github.event.inputs.version }}-dev
      ui_repo_ref: ${{ github.event.inputs.ui_repo_ref }}
      server_repo_ref: ${{ github.event.inputs.ui_repo_ref }}
      image_name_prefix: joinmarket-webui/joinmarket-webui-dev-
